name: Release Preparation Workflow
description: Comprehensive workflow for preparing and deploying a new release
version: 1.0.0

triggers:
  - type: manual
    command: /prepare-release
  - type: scheduled
    cron: "0 10 * * FRI"  # Every Friday at 10 AM
  - type: git
    event: tag_created
    pattern: v*.*.*

inputs:
  - name: version
    description: Version number (semantic versioning)
    required: true
    pattern: ^\d+\.\d+\.\d+$

  - name: release_type
    description: Type of release
    enum: [major, minor, patch, hotfix]
    required: true

  - name: release_notes
    description: Human-readable release notes
    required: true

workflow:
  - stage: Pre-Release Validation
    description: Ensure codebase is ready for release
    tasks:
      - name: check_branch
        action: |
          Ensure on correct branch (main/master).
          Verify branch is up to date with remote.

      - name: dependency_audit
        action: |
          npm audit --production
          Check for security vulnerabilities.
          Update dependencies if needed.

      - name: check_pending_work
        action: |
          Verify no unfinished features in main.
          Check for TODO comments in code.
          Ensure all planned features are complete.

  - stage: Comprehensive Testing
    agent: qa-tester
    tasks:
      - name: run_unit_tests
        action: |
          npm run test:unit
          Ensure 100% pass rate.

      - name: run_integration_tests
        action: |
          npm run test:integration
          Verify all integrations working.

      - name: run_e2e_tests
        action: |
          npm run test:e2e
          Test complete user workflows.

      - name: check_coverage
        action: |
          npm run test:coverage
          Ensure coverage thresholds met (>80%).

      - name: performance_tests
        action: |
          Run performance benchmarks.
          Compare with previous release.
          Ensure no significant regression.

      - name: security_scan
        action: |
          npm audit
          Run security scanning tools.
          Check for vulnerabilities in code and dependencies.

    outputs:
      - test-results/
      - coverage-report/
      - performance-report.json
      - security-scan.json

  - stage: Code Quality Check
    agent: code-reviewer
    tasks:
      - name: static_analysis
        action: |
          npm run lint
          Run static code analysis.
          Fix any issues found.

      - name: type_checking
        action: |
          npm run type-check
          Ensure no TypeScript errors.

      - name: code_complexity_check
        action: |
          Analyze code complexity metrics.
          Ensure maintainability standards met.

    outputs:
      - quality-report.md

  - stage: Build Verification
    agent: devops-engineer
    tasks:
      - name: production_build
        action: |
          npm run build
          Verify production build succeeds.
          Check build output for issues.

      - name: bundle_size_check
        action: |
          Analyze bundle sizes.
          Compare with previous version.
          Warn if significant increase.

      - name: docker_image_build
        condition: deployment_uses_docker
        action: |
          docker build -t app:{{version}} .
          Verify Docker image builds successfully.

    outputs:
      - build/
      - bundle-analysis.json
      - docker-image-info.json

  - stage: Documentation Update
    tasks:
      - name: generate_changelog
        action: |
          Generate CHANGELOG.md from git commits.
          Categorize changes (Features, Bug Fixes, Breaking Changes).
          Include PR links and author credits.

      - name: update_version
        action: |
          Update version in package.json.
          Update version in other config files.

      - name: update_api_docs
        condition: has_api_changes
        action: |
          Regenerate API documentation.
          Update Swagger/OpenAPI specs.

      - name: update_readme
        action: |
          Update README with new version info.
          Add any new features to documentation.
          Update installation instructions if needed.

    outputs:
      - CHANGELOG.md
      - package.json
      - docs/

  - stage: Release Notes Creation
    tasks:
      - name: compile_release_notes
        action: |
          Create comprehensive release notes including:
          - New features
          - Bug fixes
          - Breaking changes
          - Migration guide
          - Deprecation notices
          - Contributors

      - name: highlight_breaking_changes
        condition: release_type === 'major'
        action: |
          Clearly document all breaking changes.
          Provide migration instructions.
          Include code examples for changes.

    outputs:
      - RELEASE_NOTES.md

  - stage: Version Tagging
    tasks:
      - name: commit_version_changes
        action: |
          git add .
          git commit -m "chore: bump version to {{version}}"

      - name: create_git_tag
        action: |
          git tag -a v{{version}} -m "Release v{{version}}"

      - name: push_changes
        action: |
          git push origin main
          git push origin v{{version}}

  - stage: Build Artifacts
    agent: devops-engineer
    tasks:
      - name: create_release_build
        action: |
          npm run build:production
          Create optimized production build.

      - name: package_artifacts
        action: |
          Create distribution packages.
          Zip build artifacts.
          Generate checksums.

      - name: publish_docker_image
        condition: deployment_uses_docker
        action: |
          docker tag app:{{version}} registry/app:{{version}}
          docker tag app:{{version}} registry/app:latest
          docker push registry/app:{{version}}
          docker push registry/app:latest

    outputs:
      - dist/
      - artifacts/
      - checksums.txt

  - stage: Deployment to Staging
    agent: devops-engineer
    tasks:
      - name: deploy_to_staging
        action: |
          Deploy release to staging environment.
          Run smoke tests on staging.

      - name: staging_validation
        action: |
          Verify all features work on staging.
          Check integrations and external services.
          Monitor for errors in staging logs.

    outputs:
      - staging-deployment-log.txt
      - staging-test-results.json

  - stage: Final Approval
    tasks:
      - name: approval_checklist
        checklist:
          - All tests passing (unit, integration, e2e)
          - Code coverage meets threshold
          - No security vulnerabilities
          - Performance benchmarks met
          - Documentation updated
          - CHANGELOG.md complete
          - Release notes written
          - Staging deployment successful
          - Breaking changes documented
          - Migration guide prepared (if needed)

      - name: stakeholder_approval
        action: |
          Request approval from stakeholders.
          Share release notes and test results.
          Confirm deployment timing.

  - stage: Production Deployment
    agent: devops-engineer
    tasks:
      - name: create_github_release
        action: |
          gh release create v{{version}} \
            --title "Release v{{version}}" \
            --notes-file RELEASE_NOTES.md \
            ./dist/*

      - name: deploy_to_production
        action: |
          Execute production deployment.
          Follow blue-green or canary deployment strategy.

      - name: monitor_deployment
        action: |
          Monitor deployment progress.
          Watch error rates and performance metrics.
          Be ready to rollback if issues detected.

      - name: smoke_tests_production
        action: |
          Run smoke tests on production.
          Verify critical features working.

    outputs:
      - production-deployment-log.txt
      - monitoring-dashboard-link.txt

  - stage: Post-Deployment
    tasks:
      - name: announcement
        action: |
          Announce release to team and users.
          Share release notes.
          Highlight key features.

      - name: update_status_page
        action: |
          Update status page with release info.
          Note any maintenance windows.

      - name: monitor_metrics
        action: |
          Monitor key metrics for 24-48 hours:
          - Error rates
          - Performance metrics
          - User feedback
          - Resource utilization

      - name: create_next_milestone
        action: |
          Create milestone for next release.
          Plan upcoming features.

notifications:
  on_success:
    - type: slack
      channel: "#releases"
      message: "Version {{version}} successfully released to production!"

    - type: email
      to: team@company.com
      subject: "Release v{{version}} Deployed"

  on_failure:
    - type: slack
      channel: "#releases"
      message: "Release {{version}} failed! Manual intervention required."

    - type: pagerduty
      severity: high

rollback_plan:
  - Revert git tag and commits
  - Deploy previous version to production
  - Restore database from backup if needed
  - Notify stakeholders
  - Create postmortem document

metrics:
  - deployment_duration
  - tests_passed_count
  - code_coverage_percentage
  - bundle_size_kb
  - deployment_success_rate
